// react-chat/src/App.js
import React, { useState, useEffect, useRef } from 'react';
import io from 'socket.io-client';
import './App.css';

function App() {
  const [socket, setSocket] = useState(null);
  const [username, setUsername] = useState('');
  const [hasJoined, setHasJoined] = useState(false);
  const [messages, setMessages] = useState([]);
  const [inputValue, setInputValue] = useState('');
  const [isConnected, setIsConnected] = useState(false);
  const [onlineUsers, setOnlineUsers] = useState([]);
  const [typingUsers, setTypingUsers] = useState([]);
  const [isTyping, setIsTyping] = useState(false);

  const messagesEndRef = useRef(null);
  const typingTimeoutRef = useRef(null);
  const usernameInputRef = useRef(null);

  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [messages]);

  useEffect(() => {
    usernameInputRef.current?.focus();
  }, []);

  const joinChat = () => {
    if (!username.trim()) return;

    const socketUrl = window.location.protocol === 'https:'
      ? `wss://${window.location.hostname}:3002`
      : 'http://localhost:3002';

    const newSocket = io(socketUrl, {
      transports: ['websocket', 'polling']
    });

    newSocket.on('connect', () => {
      console.log('Connected to Socket.io');
      setIsConnected(true);
      newSocket.emit('join', { username: username.trim() });
    });

    newSocket.on('welcome', (data) => {
      setHasJoined(true);
    });

    newSocket.on('history', (data) => {
      setMessages(data.messages);
    });

    newSocket.on('message', (data) => {
      setMessages(prev => [...prev, { ...data, type: 'message' }]);
    });

    newSocket.on('system', (data) => {
      setMessages(prev => [...prev, { ...data, type: 'system' }]);
    });

    newSocket.on('user_list', (data) => {
      setOnlineUsers(data.users);
    });

    newSocket.on('typing_indicator', (data) => {
      setTypingUsers(data.typingUsers);
    });

    newSocket.on('disconnect', () => {
      setIsConnected(false);
    });

    setSocket(newSocket);
  };

  const sendMessage = () => {
    if (!inputValue.trim() || !socket) return;

    socket.emit('message', { text: inputValue.trim() });
    setInputValue('');

    if (isTyping) {
      socket.emit('stop_typing');
      setIsTyping(false);
    }
  };

  const handleInputChange = (e) => {
    setInputValue(e.target.value);

    if (!socket || !isConnected) return;

    if (!isTyping) {
      socket.emit('typing');
      setIsTyping(true);
    }

    if (typingTimeoutRef.current) {
      clearTimeout(typingTimeoutRef.current);
    }

    typingTimeoutRef.current = setTimeout(() => {
      socket.emit('stop_typing');
      setIsTyping(false);
    }, 2000);
  };

  const formatTime = (timestamp) => {
    const date = new Date(timestamp);
    return date.toLocaleTimeString('en-US', {
      hour: '2-digit',
      minute: '2-digit'
    });
  };

  // ========================================================================
  // @MENTION FEATURE - React Implementation
  // Much cleaner than Vanilla! Uses functional components and JSX
  // ========================================================================

  const parseMentions = (text) => {
    // Extract all @mentions
    const mentionRegex = /@(\w+)/g;
    return text.match(mentionRegex) || [];
  };

  const isMentioned = (text, currentUser) => {
    // Check if current user is mentioned
    const mentionRegex = new RegExp(`@${currentUser}\\b`, 'gi');
    return mentionRegex.test(text);
  };

  const renderMessageText = (text) => {
    // Split text by @mentions and render with highlighting
    const parts = text.split(/(@\w+)/g);

    return parts.map((part, index) => {
      if (part.match(/^@\w+$/)) {
        // This is a mention - highlight it
        return (
          <span key={index} className="mention-highlight">
            {part}
          </span>
        );
      }
      return part;
    });
  };

  const renderTypingIndicator = () => {
    const others = typingUsers.filter(u => u !== username);
    if (others.length === 0) return null;

    if (others.length === 1) {
      return `${others[0]} is typing...`;
    } else if (others.length === 2) {
      return `${others[0]} and ${others[1]} are typing...`;
    } else {
      return `${others.length} people are typing...`;
    }
  };

  if (!hasJoined) {
    return (
      <div className="modal">
        <div className="modal-content">
          <h2>⚛️ Welcome to React Chat</h2>
          <p>React.js Framework | Socket.io Protocol</p>
          <input
            ref={usernameInputRef}
            type="text"
            placeholder="Enter your name..."
            value={username}
            onChange={(e) => setUsername(e.target.value)}
            onKeyPress={(e) => e.key === 'Enter' && joinChat()}
            maxLength={20}
          />
          <button onClick={joinChat}>Join Chat</button>
        </div>
      </div>
    );
  }

  return (
    <div className="container">
      <header>
        <h1>⚛️ React Chat</h1>
        <p className="subtitle">React.js | Express.js + Socket.io</p>
        <div className={`status ${isConnected ? 'connected' : 'disconnected'}`}>
          {isConnected ? 'Connected' : 'Disconnected'}
        </div>
      </header>

      <div className="chat-layout">
        <aside className="sidebar">
          <h3>Online Users</h3>
          <div className="users-list">
            {onlineUsers.map((user, idx) => (
              <div
                key={idx}
                className={`user-item ${user.username === username ? 'you' : ''}`}
              >
                {user.username === username ? `${user.username} (you)` : user.username}
              </div>
            ))}
          </div>
        </aside>

        <div className="chat-container">
          <div className="messages">
            {messages.map((msg, idx) => {
              // ============================================================
              // PRIVATE MESSAGING - React Implementation
              // Check if this is a DM and whether to show mention badge
              // ============================================================
              const isDM = msg.isDirectMessage && msg.recipient;
              const mentioned = msg.type === 'message' && !isDM && isMentioned(msg.text, username) && msg.sender !== username;

              return msg.type === 'system' ? (
                <div key={idx} className="system-message">
                  {msg.message}
                </div>
              ) : (
                <div
                  key={idx}
                  className={`message ${msg.sender === username ? 'own-message' : ''} ${mentioned ? 'mentioned' : ''} ${isDM ? 'direct-message' : ''}`}
                >
                  <div className="message-header">
                    <span className="message-sender">
                      {msg.sender === username ? 'You' : msg.sender}
                    </span>
                    {isDM && (
                      <span className="dm-badge">
                        {msg.sender === username
                          ? `📩 Private to @${msg.recipient}`
                          : '📩 Private message'}
                      </span>
                    )}
                    {mentioned && (
                      <span className="mention-badge">@ mentioned you</span>
                    )}
                    <span className="message-time">{formatTime(msg.timestamp)}</span>
                  </div>
                  <div className="message-text">
                    {renderMessageText(msg.text)}
                  </div>
                </div>
              );
            })}
            <div ref={messagesEndRef} />
          </div>

          {renderTypingIndicator() && (
            <div className="typing-indicator">
              {renderTypingIndicator()}
            </div>
          )}

          <div className="input-container">
            <input
              type="text"
              placeholder="Type a message..."
              value={inputValue}
              onChange={handleInputChange}
              onKeyPress={(e) => e.key === 'Enter' && sendMessage()}
              disabled={!isConnected}
            />
            <button onClick={sendMessage} disabled={!isConnected}>
              Send
            </button>
          </div>
        </div>
      </div>

      <footer>
        <p>Backend: Express.js + Socket.io | Open multiple tabs!</p>
      </footer>
    </div>
  );
}

export default App;

// angular-chat/src/app/app.ts
/**
 * ANGULAR CHAT COMPONENT - EventSource + HTTP
 *
 * Frontend Framework: Angular (TypeScript)
 * Communication: Server-Sent Events (receive) + HTTP POST (send)
 *
 * KEY DIFFERENCES:
 * - TypeScript with strong typing
 * - EventSource API instead of WebSocket
 * - HTTP POST for client→server communication
 * - Component-based architecture with decorators
 * - Signals for reactive state management
 */

import { Component, OnInit, OnDestroy, signal, effect } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';

interface ChatMessage {
  id?: number;
  type: string;
  text?: string;
  message?: string;
  sender?: string;
  user_id?: string;
  timestamp: string;
  isDirectMessage?: boolean;  // PM feature
  recipient?: string;          // PM feature
}

interface User {
  user_id: string;
  username: string;
}

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './app.html',
  styleUrl: './app.css'
})
export class App implements OnInit, OnDestroy {
  // Signals for reactive state (Angular 17+ feature)
  username = signal('');
  hasJoined = signal(false);
  messages = signal<ChatMessage[]>([]);
  inputValue = signal('');
  isConnected = signal(false);
  onlineUsers = signal<User[]>([]);
  typingUsers = signal<string[]>([]);

  // Non-signal state
  userId = '';
  eventSource: EventSource | null = null;
  typingTimeout: any = null;
  isTyping = false;

  private readonly API_URL = 'http://localhost:3003/api';

  constructor(private http: HttpClient) {
    // Auto-scroll effect when messages change
    effect(() => {
      const msgs = this.messages();
      setTimeout(() => this.scrollToBottom(), 100);
    });
  }

  ngOnInit() {
    // Focus username input on load
    setTimeout(() => {
      const input = document.getElementById('username-input') as HTMLInputElement;
      input?.focus();
    }, 100);
  }

  ngOnDestroy() {
    this.disconnect();
  }

  joinChat() {
    const username = this.username().trim();
    if (!username) return;

    // Join via HTTP POST
    this.http.post<{user_id: string, username: string, history: ChatMessage[]}>
      (`${this.API_URL}/join`, { username })
      .subscribe({
        next: (response) => {
          this.userId = response.user_id;
          this.hasJoined.set(true);
          this.messages.set(response.history);

          // Connect to SSE stream
          this.connectEventSource();
        },
        error: (err) => {
          console.error('Failed to join:', err);
          alert('Failed to join chat. Please try again.');
        }
      });
  }

  connectEventSource() {
    // EventSource for receiving messages (Server-Sent Events)
    this.eventSource = new EventSource(`${this.API_URL}/events/${this.userId}`);

    this.eventSource.onopen = () => {
      console.log('✅ Connected to SSE stream');
      this.isConnected.set(true);
    };

    this.eventSource.onmessage = (event) => {
      try {
        const data = JSON.parse(event.data);
        this.handleMessage(data);
      } catch (e) {
        console.error('Failed to parse SSE message:', e);
      }
    };

    this.eventSource.onerror = (error) => {
      console.error('SSE error:', error);
      this.isConnected.set(false);
    };
  }

  handleMessage(data: any) {
    switch (data.type) {
      case 'message':
        this.messages.update(msgs => [...msgs, data]);
        break;

      case 'system':
        this.messages.update(msgs => [...msgs, data]);
        break;

      case 'user_list':
        this.onlineUsers.set(data.users);
        break;

      case 'typing_indicator':
        this.typingUsers.set(data.typing_users || []);
        break;
    }
  }

  sendMessage() {
    const text = this.inputValue().trim();
    if (!text) return;

    // Send via HTTP POST (not WebSocket!)
    this.http.post(`${this.API_URL}/message`, {
      user_id: this.userId,
      text: text
    }).subscribe({
      next: () => {
        this.inputValue.set('');

        // Clear typing indicator
        if (this.isTyping) {
          this.stopTyping();
        }
      },
      error: (err) => {
        console.error('Failed to send message:', err);
      }
    });
  }

  onInputChange(value: string) {
    this.inputValue.set(value);

    if (!this.isConnected()) return;

    // Don't send typing if input is empty
    if (!value.trim()) {
      if (this.isTyping) {
        this.stopTyping();
      }
      return;
    }

    // Start typing
    if (!this.isTyping) {
      this.isTyping = true;
      this.http.post(`${this.API_URL}/typing`, {
        user_id: this.userId,
        is_typing: true
      }).subscribe();
    }

    // Debounce - stop typing after 2 seconds
    if (this.typingTimeout) {
      clearTimeout(this.typingTimeout);
    }

    this.typingTimeout = setTimeout(() => {
      this.stopTyping();
    }, 2000);
  }

  stopTyping() {
    if (!this.isTyping) return;

    this.isTyping = false;
    this.http.post(`${this.API_URL}/typing`, {
      user_id: this.userId,
      is_typing: false
    }).subscribe();
  }

  disconnect() {
    if (this.eventSource) {
      this.eventSource.close();
      this.eventSource = null;
    }

    if (this.typingTimeout) {
      clearTimeout(this.typingTimeout);
    }
  }

  formatTime(timestamp: string): string {
    const date = new Date(timestamp);
    return date.toLocaleTimeString('en-US', {
      hour: '2-digit',
      minute: '2-digit'
    });
  }

  // ========================================================================
  // @MENTION FEATURE - Angular Implementation
  // TypeScript provides compile-time type safety!
  // Notice how we return typed objects instead of raw strings
  // ========================================================================

  isMentioned(text: string | undefined): boolean {
    if (!text) return false;
    // Check if current user is mentioned
    const mentionRegex = new RegExp(`@${this.username()}\\b`, 'gi');
    return mentionRegex.test(text);
  }

  parseMentions(text: string): string[] {
    // Extract all @mentions and return as array
    const mentionRegex = /@(\w+)/g;
    return text.match(mentionRegex) || [];
  }

  renderMessageText(text: string): {type: 'text' | 'mention', content: string}[] {
    // Split text into parts for rendering with type safety
    const parts = text.split(/(@\w+)/g);

    return parts
      .filter(part => part.length > 0)
      .map(part => ({
        type: part.match(/^@\w+$/) ? 'mention' as const : 'text' as const,
        content: part
      }));
  }

  getTypingIndicator(): string | null {
    const currentUsername = this.username();
    const others = this.typingUsers().filter(u => u !== currentUsername);

    if (others.length === 0) return null;
    if (others.length === 1) return `${others[0]} is typing...`;
    if (others.length === 2) return `${others[0]} and ${others[1]} are typing...`;
    return `${others.length} people are typing...`;
  }

  isOwnMessage(msg: ChatMessage): boolean {
    return msg.user_id === this.userId;
  }

  isCurrentUser(user: User): boolean {
    return user.user_id === this.userId;
  }

  // ========================================================================
  // PRIVATE MESSAGING FEATURE - Angular Implementation
  // TypeScript ensures type safety for DM properties
  // ========================================================================
  isDirectMessage(msg: ChatMessage): boolean {
    return msg.isDirectMessage === true && !!msg.recipient;
  }

  private scrollToBottom() {
    const messagesContainer = document.querySelector('.messages');
    if (messagesContainer) {
      messagesContainer.scrollTop = messagesContainer.scrollHeight;
    }
  }

  onEnterPress(event: KeyboardEvent) {
    if (event.key === 'Enter') {
      this.sendMessage();
    }
  }

  onUsernameEnter(event: KeyboardEvent) {
    if (event.key === 'Enter') {
      this.joinChat();
    }
  }
}
